---
title: "Analysis for separate movements"
author: "Juliana Dániel Ferreira"
date: "4 december 2020"
output: html_document
---

```{r}
#rm(list=ls())
library(here)
library(tidyverse)
library(vegan)
library(lattice)
library(ggpubr)
library(lme4)
library(DHARMa)
library(interactions)
library(jtools)
library(emmeans)
library(visreg)

```

```{r load data, include=FALSE}
direction.0 <- read.csv2(here("data", "database_models.csv" ))
str(direction.0)
direction <- direction.0 %>% 
  mutate(Site = as.factor(Site)) %>% 
  mutate(Road.verge = as.factor(Road.verge)) %>% 
  rename(traffic = Traffic.int) %>% 
  rename(trials = Total.no..of.flowers) %>% 
  rename(successes = Number.marked) %>% 
  mutate(Same.side = as.factor(Same.side)) %>% 
  mutate(Direction = as.factor(Direction)) %>% 
  rename(distance = Distance.to.marked..m.) %>%
  rename(insects = Insect.abundance) %>% 
  rename(flower.abund = Number.of.flowers) %>% 
  mutate(failures = trials - successes) %>% 
  mutate(obs = c(1:240))
str(direction)

```


```{r}
# Final models:
# Total across: select only observations where the marked flower was on the opposite side of the road (Same side=N), exclude group C.

across.db <- direction %>% 
  filter(., Same.side == "N") %>% 
  filter(., !Group %in% c("1C", "2C")) 
str(across.db)

across.mod <- glmer(formula = cbind(successes, failures) ~ Road.verge * scale(traffic) + scale(distance) +
                    log10(insects+1) + (1 | Site) + (1 | obs), 
                  family = "binomial", data = across.db)

summary(across.mod)
mod_dharma <- across.mod %>% simulateResiduals(n=1000)
plot(mod_dharma)#, quantreg = F) #the quantile regression didn't work so I supressed it
plotResiduals(predict(across.mod), mod_dharma$scaledResiduals)
unique(predict(across.mod))
plotResiduals(mod_dharma, direction$Environment1, quantreg = F)
testDispersion(mod_dharma)
hist(mod_dharma)
hist(resid(direction.mod))
mod_dharma %>% testDispersion()
mod_dharma %>% testZeroInflation()

visreg(across.mod, xvar="traffic", by="Road.verge", scale="response", 
       strip.names=c("Species Poor", "Species Rich"))

# Total along: select only observations where the marked flower was on the same side of the road (Same side=Y), exclude group C
along.db <- direction %>% 
  filter(., Same.side == "Y") %>% 
  filter(., !Group %in% c("1C", "2C")) 
str(along.db)

along.mod <- glmer(formula = cbind(successes, failures) ~ Road.verge * scale(traffic) + scale(distance) +
                    log10(insects+1) + (1 | Site) , 
                  family = "binomial", data = along.db)
summary(along.mod)
mod_dharma <- along.mod %>% simulateResiduals(n=1000)
plot(mod_dharma)#, quantreg = F) #the quantile regression didn't work so I supressed it
plotResiduals(predict(along.mod), mod_dharma$scaledResiduals)
unique(predict(along.mod))
plotResiduals(mod_dharma, direction$Environment1, quantreg = F)
testDispersion(mod_dharma)
hist(mod_dharma)
hist(resid(direction.mod))
mod_dharma %>% testDispersion()
mod_dharma %>% testZeroInflation()

visreg(along.mod, xvar="traffic", by="Road.verge", scale="response", 
       strip.names=c("Species Poor", "Species Rich"))

# Total into the neighbouring: select only observations where the marked flower was on the same side of the road (Same side=Y)
neighb.across <- direction %>% 
  filter(., Same.side == "N") %>% 
  filter(., Group %in% c("1C", "2C")) 
str(neighb.across)

neighbacross.mod <- glmer(formula = cbind(successes, failures) ~ Road.verge * scale(traffic) +
                            scale(distance) + log10(insects+1) + (1 | Site), 
                  family = "binomial", data = neighb.across)
summary(neighbacross.mod)
mod_dharma <- neighbacross.mod %>% simulateResiduals(n=1000)
plot(mod_dharma)

neighb.along <- direction %>% 
  filter(., Same.side == "Y") %>% 
  filter(., Group %in% c("1C", "2C")) 
str(neighb.along)

neighbalong.mod <- glmer(formula = cbind(successes, failures) ~ Road.verge * scale(traffic) +
                            scale(distance) + log10(insects+1) + (1 | Site), 
                  family = "binomial", data = neighb.along)
summary(neighbalong.mod)
mod_dharma <- neighbalong.mod %>% simulateResiduals(n=1000)
plot(mod_dharma)

visreg(neighbalong.mod, xvar="traffic", by="Road.verge", scale="response", 
       strip.names=c("Species Poor", "Species Rich"))


```

